const shoes=[
 {id:"cream",name:"纯白低帮",kind:"极简鞋型",color:"奶油白",scene:"城市漫步",tag:"干净 · 克制 · 百搭",line:"今天不必大声，也能被看见。",desc:"利落低帮与温柔奶油色，让你在通勤、约会和周末散步之间自然切换。"},
 {id:"orange",name:"烈焰街头",kind:"厚底鞋型",color:"信号橙",scene:"聚会现场",tag:"高能 · 撞色 · 焦点",line:"把今天的存在感，调到最大。",desc:"体块感鞋底配合高饱和能量色，适合想让鞋成为整套造型中心的时刻。"},
 {id:"silver",name:"银翼未来",kind:"流线鞋型",color:"冰川银",scene:"夜间移动",tag:"未来 · 速度 · 反光",line:"比潮流先走半步，就是你的节奏。",desc:"银蓝层次和速度线条带来未来运动感，尤其适合夜间城市与科技感穿搭。"},
 {id:"olive",name:"苔原漫游",kind:"越野鞋型",color:"苔藓绿",scene:"周末出走",tag:"户外 · 抓地 · 松弛",line:"城市是起点，旷野才是方向。",desc:"可靠抓地结构与低调大地色，陪你从城市街区自然走向周末的未知路径。"},
 {id:"black",name:"暗影高帮",kind:"雕塑高帮",color:"曜石黑",scene:"午夜现场",tag:"暗黑 · 雕塑 · 强势",line:"不解释，是今晚最酷的表达。",desc:"黑色立体轮廓拥有强烈戏剧感，适合音乐现场、夜间聚会与不想低调的你。"},
 {id:"lilac",name:"紫雾复古",kind:"复古跑型",color:"雾感紫",scene:"艺术街区",tag:"复古 · 柔和 · 灵感",line:"温柔不是降低音量，而是换一种频率。",desc:"复古跑鞋比例配合轻雾紫色，为日常造型增加刚刚好的浪漫和艺术感。"},
 {id:"cobalt",name:"钴蓝脉冲",kind:"机能跑型",color:"电光蓝",scene:"运动挑战",tag:"机能 · 响应 · 高速",line:"今天适合突破，而不是重复。",desc:"技术感鞋面与强烈钴蓝色释放速度信号，为训练、出行和高能日程提供动力。"},
 {id:"sand",name:"沙丘经典",kind:"经典板鞋",color:"沙岩色",scene:"日常通勤",tag:"质感 · 复古 · 耐看",line:"越经得起时间，越接近真正的风格。",desc:"沙色麂皮与经典比例不抢戏却很耐看，是适合长期留在鞋柜里的稳定选手。"},
 {id:"lime",name:"荧光加速",kind:"轻量跑型",color:"酸性绿",scene:"未知派对",tag:"稀有 · 荧光 · 超现实",line:"恭喜，你摇到了今天的隐藏信号。",desc:"超现实荧光与轻量结构组成稀有组合——今天适合尝试一件平常不会做的事。"}
];
const $=s=>document.querySelector(s),reelsEl=$("#reels"),machine=$("#machine"),lever=$("#lever");
let current=[0,4,7],mode="daily",spinning=false,soundOn=true,pulls=Number(localStorage.getItem("soleSignalPulls")||0),timers=[];
function image(i){return `assets/shoes/${shoes[(i+shoes.length)%shoes.length].id}.png`}
function renderReels(){reelsEl.innerHTML=current.map((center,col)=>`<div class="reel" data-reel="${col}"><div class="reel-items">${[-1,0,1].map(off=>`<div class="reel-item"><img src="${image(center+off)}" alt="${shoes[(center+off+9)%9].name}"></div>`).join("")}</div></div>`).join("")}
function beep(freq=220,duration=.06){if(!soundOn)return;try{const ctx=new(window.AudioContext||window.webkitAudioContext)(),o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=freq;o.type="sine";g.gain.setValueAtTime(.045,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+duration);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+duration)}catch(e){}}
function pickIndex(col){const pools={daily:[[0,5,7],[0,7,3],[0,7,5]],bold:[[1,4,6],[1,2,8],[1,4,8]],wild:[[0,1,2,3,4,5,6,7,8],[0,1,2,3,4,5,6,7,8],[0,1,2,3,4,5,6,7,8]]};const pool=pools[mode][col];return pool[Math.floor(Math.random()*pool.length)]}
function spin(){if(spinning)return;spinning=true;timers.forEach(clearInterval);timers=[];machine.classList.remove("winner","rare");$("#resultPanel").classList.add("hidden");lever.classList.add("pulled");$("#statusText").textContent="MIXING YOUR SIGNAL...";document.querySelectorAll(".reel").forEach(r=>r.classList.add("spinning"));beep(120,.14);let targets=[pickIndex(0),pickIndex(1),pickIndex(2)];pulls++;localStorage.setItem("soleSignalPulls",pulls);$("#pullCount").textContent=String(pulls).padStart(3,"0")+" PULLS";$("#streakCount").textContent=pulls;if(pulls>=3&&Math.random()<.22)targets=[8,8,8];
 current.forEach((_,col)=>{timers[col]=setInterval(()=>{current[col]=(current[col]+1)%9;const reel=document.querySelector(`[data-reel="${col}"] .reel-items`);reel.innerHTML=[-1,0,1].map(off=>`<div class="reel-item"><img src="${image(current[col]+off)}" alt=""></div>`).join("");beep(95+col*18,.025)},74+col*12);setTimeout(()=>stopReel(col,targets[col]),850+col*430)});
}
function stopReel(col,target){clearInterval(timers[col]);current[col]=target;const reel=document.querySelector(`[data-reel="${col}"]`);reel.classList.remove("spinning");reel.querySelector(".reel-items").innerHTML=[-1,0,1].map(off=>`<div class="reel-item"><img src="${image(target+off)}" alt="${shoes[(target+off+9)%9].name}"></div>`).join("");beep(260+col*90,.14);if(col===2)finish()}
function finish(){spinning=false;lever.classList.remove("pulled");machine.classList.add("winner");const exact=current[0]===current[1]&&current[1]===current[2],chosen=exact?current[0]:current.reduce((a,b)=>a+b,0)%9,d=shoes[chosen],rare=exact||chosen===8;machine.classList.toggle("rare",rare);$("#statusText").textContent=rare?"RARE SIGNAL UNLOCKED!":"SIGNAL LOCKED · CLAIM IT";$("#rarity").textContent=rare?"★ RARE DROP · HIDDEN SIGNAL":"TODAY'S SNEAKER SIGNAL";$("#resultTitle").textContent=d.name;$("#resultCode").textContent=`0${chosen+1}`;$("#resultImage").src=image(chosen);$("#matchRate").textContent=`MATCH ${rare?99:88+Math.floor(Math.random()*9)}%`;$("#resultTags").textContent=`${current.map(i=>shoes[i].kind.replace("鞋型","")).join(" × ")} · ${d.tag}`;$("#resultLine").textContent=d.line;$("#resultDescription").textContent=`你摇中了「${shoes[current[0]].kind}、${shoes[current[1]].color}、${shoes[current[2]].scene}」的碰撞组合。${d.desc}`;$("#resultPanel").classList.remove("hidden");setTimeout(()=>$("#resultPanel").scrollIntoView({behavior:"smooth",block:"center"}),420);beep(rare?660:480,.32)}
document.querySelectorAll(".modes button").forEach(b=>b.onclick=()=>{if(spinning)return;document.querySelectorAll(".modes button").forEach(x=>x.classList.remove("active"));b.classList.add("active");mode=b.dataset.mode;$("#modeDisplay").textContent=mode.toUpperCase();beep(330,.06)});
lever.onclick=spin;$("#againBtn").onclick=()=>{window.scrollTo({top:document.querySelector(".game-wrap").offsetTop-20,behavior:"smooth"});setTimeout(spin,450)};$("#soundBtn").onclick=()=>{soundOn=!soundOn;$("#soundBtn").textContent=soundOn?"SOUND ON":"SOUND OFF"};
$("#shareBtn").onclick=()=>{const text=`我在 SOLE SIGNAL 摇到了「${$("#resultTitle").textContent}」！${$("#resultLine").textContent} 你也来试试：${location.href}`;navigator.clipboard.writeText(text).then(()=>{const t=$("#toast");t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)})};
document.addEventListener("keydown",e=>{if(e.code==="Space"&&!e.repeat){e.preventDefault();spin()}});$("#pullCount").textContent=String(pulls).padStart(3,"0")+" PULLS";$("#streakCount").textContent=pulls;renderReels();
