const moods={
 minimal:{index:"01",name:"静默极简派",en:"QUIET MINIMALIST",symbol:"○",color:"#242424",soft:"#e9e5dd",shoe:"#d8d0c2",kicker:"你相信，真正耐看的东西不需要大声。",desc:"你重视比例、材质与长期搭配价值。比起追逐每一波热度，你更愿意让一双干净、克制的鞋成为衣橱里的稳定坐标。",shoes:[["MONO 01","奶油低帮板鞋",["低饱和","皮革","日常"],"干净鞋面与微宽楦型，适合融入几乎所有日常搭配。","#d8d0c2"],["LINE 02","灰白复古训练鞋",["复古","轻量","通勤"],"低调层次和舒适脚感，让简单不等于无聊。","#aaa69f"],["FORM 03","黑白结构便鞋",["结构感","黑白","城市"],"用轮廓和留白制造辨识度，适合克制的城市造型。","#484848"]]},
 street:{index:"02",name:"高能街头派",en:"BOLD STREET SIGNAL",symbol:"✦",color:"#9b321c",soft:"#f0d8cf",shoe:"#ef4b25",kicker:"你穿的不是安全答案，而是自己的音量。",desc:"你喜欢有态度的轮廓、醒目的配色和能成为造型中心的单品。一双鞋对你来说，是进入现场之前就已经发出的信号。",shoes:[["PULSE 88","橙红厚底街头鞋",["厚底","撞色","焦点"],"夸张体块和高能配色，第一眼就建立造型重心。","#ef4b25"],["BLOCK 24","拼接滑板鞋",["滑板","拼接","耐磨"],"宽楦与多材质拼接，把街头感落在真实穿着里。","#3652b7"],["NIGHT TAG","夜光高帮鞋",["高帮","反光","夜行"],"暗色鞋身加反光细节，夜晚比白天更有存在感。","#252735"]]},
 future:{index:"03",name:"未来机能派",en:"FUTURE MOTION",symbol:"⌁",color:"#28576c",soft:"#dae7ea",shoe:"#8bb8c7",kicker:"你总在寻找下一步，而不是重复上一步。",desc:"你会被新材料、速度感线条与功能细节吸引。轻量、响应和实验性设计，比经典故事更能打动你。",shoes:[["VECTOR X","银蓝响应跑鞋",["缓震","银蓝","速度"],"流线鞋面和分区中底，为快速移动保留轻盈响应。","#8bb8c7"],["GRID AIR","网格未来训练鞋",["透气","模块","训练"],"网格结构配合模块化鞋底，科技感来自真实功能。","#d6e1e5"],["PHASE 04","无缝套袜运动鞋",["无缝","轻量","弹性"],"包裹式鞋面减少干扰，适合追求干净机能感的人。","#657780"]]},
 trail:{index:"04",name:"城市越野派",en:"URBAN TRAIL SOUL",symbol:"△",color:"#405d38",soft:"#dfe8d9",shoe:"#71855c",kicker:"城市是日常，旷野是你留给自己的出口。",desc:"你喜欢可靠、有抓地力、又能自然进入城市穿搭的鞋。泥土色、实用结构和随时出发的感觉，会让你格外安心。",shoes:[["RIDGE 07","苔绿城市越野鞋",["抓地","苔绿","全天候"],"户外大底与城市比例兼得，从通勤到短途徒步都自然。","#71855c"],["DUST PATH","沙岩复古徒步鞋",["麂皮","沙色","复古"],"柔和大地色搭配结实鞋底，耐看又有探索气质。","#a18159"],["RAIN FIELD","防泼水轻徒步鞋",["防泼水","轻量","旅行"],"应对天气变化的轻量选择，适合说走就走的周末。","#445748"]]}
};
const questions=[
 {e:"穿搭第一原则",q:"挑鞋时，你最先注意什么？",o:[["轮廓干净，能穿很久","minimal"],["够不够抢眼、有态度","street"],["科技材料和脚感表现","future"],["耐穿、抓地、能走远","trail"]]},
 {e:"周末信号",q:"理想周末更接近哪一幕？",o:[["咖啡店、展览和安静街区","minimal"],["演出、球场和朋友聚会","street"],["夜跑、训练或探索新设备","future"],["公园、山路或临时小旅行","trail"]]},
 {e:"配色直觉",q:"哪组颜色最像你的鞋柜？",o:[["黑、白、灰、奶油色","minimal"],["高饱和撞色与大胆印花","street"],["银色、冰蓝和半透明材质","future"],["苔绿、沙色和大地色","trail"]]},
 {e:"最后一拍",q:"你希望别人如何形容这双鞋？",o:[["很耐看，越看越舒服","minimal"],["一眼就记住，太有型了","street"],["像从未来带回来的","future"],["看起来随时可以出发","trail"]]}
];
let step=0,answers=[];
const $=s=>document.querySelector(s),intro=$("#intro"),quiz=$("#quiz"),result=$("#result");
function home(){step=0;answers=[];quiz.classList.add("hidden");result.classList.add("hidden");intro.classList.remove("hidden");scrollTo({top:0,behavior:"smooth"})}
function renderQuestion(){const x=questions[step];$("#stepNumber").textContent=`0${step+1}`;$("#progressBar").style.width=`${(step+1)*25}%`;$("#questionEyebrow").textContent=x.e;$("#questionTitle").textContent=x.q;$("#backBtn").disabled=step===0;$("#options").innerHTML=x.o.map(([label,mood],i)=>`<button data-mood="${mood}" class="${answers[step]===mood?"selected":""}"><span>0${i+1}</span><strong>${label}</strong><i>↗</i></button>`).join("");document.querySelectorAll("#options button").forEach(b=>b.onclick=()=>choose(b.dataset.mood))}
function choose(mood){answers[step]=mood;if(step<3){step++;setTimeout(renderQuestion,120)}else showResult()}
function showResult(){const score={minimal:0,street:0,future:0,trail:0};answers.forEach(x=>score[x]++);const winner=Object.keys(score).sort((a,b)=>score[b]-score[a]||Object.keys(score).indexOf(a)-Object.keys(score).indexOf(b))[0],d=moods[winner];intro.classList.add("hidden");quiz.classList.add("hidden");result.classList.remove("hidden");result.style.setProperty("--mood",d.color);result.style.setProperty("--mood-soft",d.soft);result.style.setProperty("--shoe",d.shoe);$("#resultIndex").textContent=d.index;$("#resultName").textContent=d.name;$("#resultEn").textContent=d.en;$("#resultKicker").textContent=d.kicker;$("#resultDesc").textContent=d.desc;$("#resultSymbol").textContent=d.symbol;$("#cards").innerHTML=d.shoes.map((s,i)=>`<article class="card"><div class="mini-shoe"><i style="--card:${s[4]}"></i></div><small>MATCH ${98-i*6}%</small><h3>${s[0]} · ${s[1]}</h3><div class="tags">${s[2].map(t=>`<span>${t}</span>`).join("")}</div><p>${s[3]}</p></article>`).join("");$("#copyBtn").onclick=()=>navigator.clipboard?.writeText(`我的球鞋人格是「${d.name}」——${d.kicker}`).then(()=>{$("#copyBtn span").textContent="已复制结果 ✓"});scrollTo({top:0,behavior:"smooth"})}
$("#startBtn").onclick=()=>{intro.classList.add("hidden");quiz.classList.remove("hidden");renderQuestion()};$("#backBtn").onclick=()=>{if(step>0){step--;renderQuestion()}};$("#restartBtn").onclick=home;document.querySelectorAll("[data-home]").forEach(x=>x.onclick=home);
